call plug#begin()

"basic stuff
Plug 'wellle/targets.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-rsi'
Plug 'jiangmiao/auto-pairs'
Plug 'machakann/vim-highlightedyank'

"fzf
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

Plug 'dart-lang/dart-vim-plugin'

"git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

"lsp
Plug 'neoclide/coc.nvim', {'branch': 'release'}

"command complete
Plug 'gelguy/wilder.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'roxma/nvim-yarp'

" snippets
Plug 'rafamadriz/friendly-snippets'
Plug 'Neevash/awesome-flutter-snippets'

" vim status line
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'github/copilot.vim'

call plug#end()

set relativenumber
set number
set hlsearch
set background=dark

nmap <C-s>  :update<CR>
nmap <space>co :copen<CR>
nmap <space>cc :ccl<CR>
nmap <space>cl :cli<CR>
nmap <space>lo :lopen<CR>
nmap <space>lc :lcl<CR>
nmap <space>ll :lli<CR>

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.9 } }
nmap <space>p :GFiles<CR>
nmap <space><space> :Files<CR>
nmap <space>fb :Buffers<CR>
nmap <space>sg :Rg<CR>
nmap <space>fo :History<CR>
nmap <space>sh :Helptags<CR>

let g:highlightedyank_highlight_duration = 200

"nmap k	 "v:count == 0 ? 'gk' : 'k'"
"nmap j	 "v:count == 0 ? 'gj' : 'j'"

source ~/dotfiles/vim/coc_setup.vim
source ~/dotfiles/nvim/plugin/toggle-term.vim

call wilder#setup({'modes': [':', '/', '?']})
" 'highlighter' : applies highlighting to the candidates
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'highlighter': wilder#basic_highlighter(),
      \ }))

let g:copilot_node_command = '/usr/local/opt/node@16/bin/node'

set laststatus=3
