call plug#begin()

"basic stuff
Plug 'wellle/targets.vim'
Plug 'tpope/vim-tbone'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-scriptease'
Plug 'jiangmiao/auto-pairs'
Plug 'machakann/vim-highlightedyank'
Plug 'sjl/clam.vim'

"fzf
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

"git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

"lsp
Plug 'neoclide/coc.nvim', {'branch': 'release'}

"Airline
Plug 'vim-airline/vim-airline'

call plug#end()

set relativenumber
set number
set hlsearch
set background=dark

"nmap <C-s>  :update<CR>
nmap <space>co :copen<CR>
nmap <space>cc :ccl<CR>
nmap <space>cl :cli<CR>
nmap <space>lo :lopen<CR>
nmap <space>lc :lcl<CR>
nmap <space>ll :lli<CR>

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.9 } }
nmap <space>p :GFiles<CR>
nmap <space><space> :Files<CR>
nmap <space>fb :Buffers<CR>
nmap <space>sg :Rg<CR>
nmap <space>fo :History<CR>
nmap <space>sh :Helptags<CR>

let g:highlightedyank_highlight_duration = 200

source ~/dotfiles/vim/coc_setup.vim
"source ~/dotfiles/nvim/plugin/monkey_term.lua

set laststatus=2
