function! UpdateRemotePlugins(...)
    " Needed to refresh runtime files
    let &rtp=&rtp
    UpdateRemotePlugins
endfunction

call plug#begin()

"lsp
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

packadd termdebug packadd cfilter

if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
endif

let g:termdebug_config = {}
let g:termdebug_config['command'] = "lldb"

set relativenumber
set number
set hlsearch
set background=dark
set clipboard+=unnamedplus

"nmap <C-s>  :update<CR>
nmap <space>co :copen<CR>
nmap <space>cc :ccl<CR>
nmap <space>cl :cli<CR>
nmap <space>lo :lopen<CR>
nmap <space>lc :lcl<CR>
nmap <space>ll :lli<CR>

lua << EOF
  local highlight_group = vim.api.nvim_create_augroup('YankHighlight', { clear = true })
  vim.api.nvim_create_autocmd('TextYankPost', {
    callback = function()
      vim.highlight.on_yank()
    end,
    group = highlight_group,
    pattern = '*',
  })
EOF

source ~/dotfiles/vim/coc_setup.vim
source ~/dotfiles/nvim/lua/ts.lua
source ~/dotfiles/nvim/lua/telescope_setup.lua
source ~/dotfiles/nvim/lua/telescope_setup.lua
source ~/dotfiles/nvim/lua/comment_setup.lua
source ~/dotfiles/nvim/lua/gitsigns_setup.lua

lua << EOF
    if vim.version().minor >= 8 then
      vim.o.winbar = '%m %f'
    end
EOF

set laststatus=3
set cmdheight=1

hi Pmenu ctermbg=none ctermfg=white
hi SignColumn ctermbg=none
hi WinSeparator ctermbg=none
hi DiffAdd ctermbg=none ctermfg=green
hi DiffDelete ctermbg=none ctermfg=red
hi DiffChange ctermbg=none ctermfg=yellow
