require('colorbuddy').colorscheme('gruvbuddy')
vim.api.nvim_set_hl(0, 'CursorLine', { underline = true, bg = nil })
vim.api.nvim_set_hl(0, 'Winbar', { bg = nil, fg = 'yellow' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchDefault', { bg = nil, fg = '#f2904b' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzyDefault', { bg = nil, fg = '#f2904b' })
vim.api.nvim_set_hl(0, 'WinbarNC', { bg = nil })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = nil })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = 'pink' })
